### ISSUE TITLE
Request : If show seconds is set to false, please hide the seconds from display 

### ISSUE THREAD

**Issue by razorhenry1** [h2qutc/angular-material-components#100]
Hi,
If show seconds is set to false, there is no use to show seconds once the popover closes. 
Right now this time picker shows the following date time : 8/20/2020, 17:00:00

Is there any way to hide seconds in this view and get only 8/20/2020, 17:00 ?

**Comment by imvikaskohli** [comment]
I got by writing manually DateTime Format
```
import { NgxMatDatetimePickerModule, NgxMatTimepickerModule, NgxMatNativeDateModule, NgxMatDateFormats } from '@angular-material-components/datetime-picker';
import { NgxMatMomentModule } from '@angular-material-components/moment-adapter';
export const MY_FORMAT = 'DD/MM/YYYY HH:mm A';
// If using Moment
const CUSTOM_MOMENT_FORMATS: NgxMatDateFormats = {
  parse: {
    dateInput: MY_FORMAT,
  },
  display: {
    dateInput: MY_FORMAT,
    monthYearLabel: 'MMM YYYY',
    dateA11yLabel: 'LL',
    monthYearA11yLabel: 'MMMM YYYY',
  },
};
providers: [MatSnackBar, TeamService,
    {provide: MY_FORMAT, useValue: CUSTOM_MOMENT_FORMATS}
  ]
```
![image](https://user-images.githubusercontent.com/23357854/91181741-ee2d7d00-e706-11ea-9891-3edf3a759ac5.png)

And The Value set as 
![image](https://user-images.githubusercontent.com/23357854/91181830-07cec480-e707-11ea-9eb5-893d7c589029.png)

Source:- Please check this comment [How to change the date-time format ](https://github.com/h2qutc/angular-material-components/issues/27#issuecomment-644985390)

**Comment by razorhenry1** [comment]
> I got by writing manually DateTime Format
> 
> ```
> import { NgxMatDatetimePickerModule, NgxMatTimepickerModule, NgxMatNativeDateModule, NgxMatDateFormats } from '@angular-material-components/datetime-picker';
> import { NgxMatMomentModule } from '@angular-material-components/moment-adapter';
> export const MY_FORMAT = 'DD/MM/YYYY HH:mm A';
> // If using Moment
> const CUSTOM_MOMENT_FORMATS: NgxMatDateFormats = {
>   parse: {
>     dateInput: MY_FORMAT,
>   },
>   display: {
>     dateInput: MY_FORMAT,
>     monthYearLabel: 'MMM YYYY',
>     dateA11yLabel: 'LL',
>     monthYearA11yLabel: 'MMMM YYYY',
>   },
> };
> providers: [MatSnackBar, TeamService,
>     {provide: MY_FORMAT, useValue: CUSTOM_MOMENT_FORMATS}
>   ]
> ```
> 
> ![image](https://user-images.githubusercontent.com/23357854/91181741-ee2d7d00-e706-11ea-9891-3edf3a759ac5.png)
> 
> And The Value set as
> ![image](https://user-images.githubusercontent.com/23357854/91181830-07cec480-e707-11ea-9eb5-893d7c589029.png)
> 
> Source:- Please check this comment [How to change the date-time format ](https://github.com/h2qutc/angular-material-components/issues/27#issuecomment-644985390)

Hi imvikaskohli , thanks for the response. I will try this once , but my question is, the output of your still has seconds in the value even though the format was : 'DD/MM/YYYY HH:mm A' . I don't want seconds to be listed.

**Comment by FrancoisGodin1** [comment]
Did you manage to resolve this?

**Comment by Lonli-Lokli** [comment]
@h2qutc Can you please fix it? 

Seems like it's easy to reproduce - disable time picker in options and set any value - input will display seconds as well. For the control without time it should behave same as Material's datepicker.

**Comment by IlBrielli** [comment]
> > I got by writing manually DateTime Format
> > ```
> > import { NgxMatDatetimePickerModule, NgxMatTimepickerModule, NgxMatNativeDateModule, NgxMatDateFormats } from '@angular-material-components/datetime-picker';
> > import { NgxMatMomentModule } from '@angular-material-components/moment-adapter';
> > export const MY_FORMAT = 'DD/MM/YYYY HH:mm A';
> > // If using Moment
> > const CUSTOM_MOMENT_FORMATS: NgxMatDateFormats = {
> >   parse: {
> >     dateInput: MY_FORMAT,
> >   },
> >   display: {
> >     dateInput: MY_FORMAT,
> >     monthYearLabel: 'MMM YYYY',
> >     dateA11yLabel: 'LL',
> >     monthYearA11yLabel: 'MMMM YYYY',
> >   },
> > };
> > providers: [MatSnackBar, TeamService,
> >     {provide: MY_FORMAT, useValue: CUSTOM_MOMENT_FORMATS}
> >   ]
> > ```
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/23357854/91181741-ee2d7d00-e706-11ea-9891-3edf3a759ac5.png)
> > And The Value set as
> > ![image](https://user-images.githubusercontent.com/23357854/91181830-07cec480-e707-11ea-9eb5-893d7c589029.png)
> > Source:- Please check this comment [How to change the date-time format ](https://github.com/h2qutc/angular-material-components/issues/27#issuecomment-644985390)
> 
> Hi imvikaskohli , thanks for the response. I will try this once , but my question is, the output of your still has seconds in the value even though the format was : 'DD/MM/YYYY HH:mm A' . I don't want seconds to be listed.

The error was on `{provide: MY_FORMAT, useValue: CUSTOM_MOMENT_FORMATS}`: is a no-sense definition.
The correct one is `{ provide: NGX_MAT_DATE_FORMATS, useValue: CUSTOM_MOMENT_FORMATS }`.

**Comment by iwwk-alex** [comment]
Guys, it's been six months, have you solved this problem? how can I hide the display of seconds in the input data? I still see the seconds.
![Uploading datetimepicker.jpg…]()

**Comment by h2qutc** [comment]
@razorhenry1 @iwwk-alex  After verifying, I think that it is not a bug. It is a comportement of the component. In fact, we use a provider called NGX_MAT_DATE_FORMATS to define how the component parse and display the selected date. 

`
export declare type NgxMatDateFormats = {
    parse: {
        dateInput: any;
    };
    display: {
        dateInput: any;
        monthYearLabel: any;
        dateA11yLabel: any;
        monthYearA11yLabel: any;
    };
};
`

So you have created a custom format to respond your demand. Feel free to check [demo stackblitz ](https://stackblitz.com/edit/demo-ngx-mat-datetime-picker-angular10), I did an example by using custom formats that works for Moment.js
You can also check the [demo and documentation](https://h2qutc.github.io/angular-material-components) for details.

**Comment by abrasat** [comment]
@h2qutc How can the date time format be customized without using the moment library? For example to display the date part as "19.01.2022" instead of the default "1/18/2022"

**Comment by avishekdr** [comment]
> isn't there anything we can do without using momentjs? My concern is adding another library on top of 1 will add an extra load.
