### ISSUE TITLE
Disabling TimePicker doesn't disable the minutes input

### ISSUE THREAD

**Issue by strahinja-gligovic** [h2qutc/angular-material-components#103]
Check out the live timepicker demo - https://h2qutc.github.io/angular-material-components/

The  spinners and the hours input are disabled but you can still manually enter minutes.

It seems the seconds are also disabled
![image](https://user-images.githubusercontent.com/31292812/91604413-e4a64e00-e96e-11ea-8f2c-7b506748b067.png)

**Comment by h2qutc** [comment]
@strahinja-gligovic  the latest version (4.x for Angular 10, 5.x for Angular 11) has already been released with correction. Feel free to check it out. Thanks for your supports.
