### ISSUE TITLE
error TS2420: Class 'NgxMatDatetimePicker<D>' incorrectly implements interface 'CanColor'.

### ISSUE THREAD

**Issue by sakthivel-ar** [h2qutc/angular-material-components#108]
I am trying to do "ng build" or "ng serve"

Steps I have tried:
-     Deleted node_modules and reinstalled through npm.
-     Performed "npm update".
-     Ran "npm install --save @angular/cdk"

I am facing the below error. Please, help me on this.
```
ERROR in node_modules/@angular-material-components/datetime-picker/lib/datetime-picker.component.d.ts:52:22 - error TS2420: Class 'NgxMatDatetimePicker<D>' incorrectly implements interface 'CanColor'.
  Property 'defaultColor' is missing in type 'NgxMatDatetimePicker<D>' but required in type 'CanColor'.

52 export declare class NgxMatDatetimePicker<D> implements OnDestroy, CanColor {
                        ~~~~~~~~~~~~~~~~~~~~

  node_modules/@angular/material/core/common-behaviors/color.d.ts:15:5
    15     defaultColor: ThemePalette | undefined;
           ~~~~~~~~~~~~
    'defaultColor' is declared here.
```

**Comment by mnesser** [comment]
Same problem here. 
Downgraded:
"@angular/material": "10.2.0" --> "10.1.3". Seems to work for me.

**Comment by Mokette** [comment]
Hello,
here are the same issue ;) : https://github.com/h2qutc/angular-material-components/issues/104

We encounter trouble to use angular-material-component with @angular/material > 10.1.3

and someone suggested a fix here : https://github.com/h2qutc/angular-material-components/pull/105 ;) but the fix hasn't been released yet

@h2qutc if you have some time to take a look at this please :)

**Comment by lovemoon23** [comment]
@h2qutc Please take time to merge #105 Thanks.

**Comment by h2qutc** [comment]
Hi All, a new version 4.0.3 of [@angular-material-components/datetime-picker](https://www.npmjs.com/package/@angular-material-components/datetime-picker) has already been released to fix this issue. 
Please check it out. Thanks.

**Comment by Mokette** [comment]
Yeah it works well ! Thanks @h2qutc :)

**Comment by rahul0755** [comment]
I'm install new packages but it's not working

Error: node_modules/ngx-mat-datetime-picker/lib/ngx-mat-datetime-picker.component.d.ts:52:22 - error TS2420: Class 'NgxMatDatetimePicker<D>' incorrectly implements interface 'CanColor'.
      Property 'defaultColor' is missing in type 'NgxMatDatetimePicker<D>' but required in type 'CanColor'.
    
    
    
    Error: node_modules/ngx-mat-datetime-picker/lib/ngx-mat-datetime-picker.component.d.ts:52:22 - error TS2420: Class 'NgxMatDatetimePicker<D>' incorrectly implements interface 'CanColor'.
      Property 'defaultColor' is missing in type 'NgxMatDatetimePicker<D>' but required in type 'CanColor'.
    
    52 export declare class NgxMatDatetimePicker<D> implements OnDestroy, CanColor {
                            ~~~~~~~~~~~~~~~~~~~~
    
      node_modules/@angular/material/core/common-behaviors/color.d.ts:15:5
        15     defaultColor: ThemePalette | undefined;
               ~~~~~~~~~~~~
        'defaultColor' is declared here.

**Comment by irfankt** [comment]
getting same error

**Comment by layinka** [comment]
Still getting this error too.

i think the color property needs to be added to NgxMatDatetimeContent<D>  also

**Comment by hasip-timurtas** [comment]
Having same error

**Comment by bable3** [comment]
i got the same error

**Comment by mrvzlo** [comment]
I have the same error

**Comment by GuilhermeRabelo** [comment]
same error!!

**Comment by aliaksandrtsiareschanka** [comment]
i got the same error

**Comment by g7crservice-rahul-kumar** [comment]
same error!!

**Comment by sumanmazumder** [comment]
i got sane issue
