### ISSUE TITLE
You provided 'undefined' where a stream was expected

### ISSUE THREAD

**Issue by damnForums** [h2qutc/angular-material-components#109]
I have tried to use the material-component-datetime-picker according to the documentation and following information contain about the environment.

Angular

- Angular version : 10.1.0

- material version : 10.1.0

- angular-material-components/moment-adapter - 4.0.1

- angular-material-components/datetime-picker - 4.0.2

Following is the code block to view datetime picker.

`<mat-form-field>
                <input matInput [ngxMatDatetimePicker]="picker" 
                                placeholder="Choose a date" 
                                [formControl]="tab._from"
                                [min]="minDate" [max]="maxDate" 
                                [disabled]="disabled">
                <mat-datepicker-toggle matSuffix [for]="picker">
                </mat-datepicker-toggle>
                <ngx-mat-datetime-picker #picker 
                  [showSpinners]="showSpinners" 
                  [showSeconds]="showSeconds"
                  [stepHour]="stepHour" [stepMinute]="stepMinute" 
                  [stepSecond]="stepSecond"
                  [touchUi]="touchUi"
                  [color]="color">
                </ngx-mat-datetime-picker>
              </mat-form-field>`

When I try to load the page, datetime-picker appears but following error appears on console.

`ERROR TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at subscribeTo (subscribeTo.js:27)
    at subscribeToResult (subscribeToResult.js:11)
    at MergeMapSubscriber._innerSub (mergeMap.js:59)
    at MergeMapSubscriber._tryNext (mergeMap.js:53)
    at MergeMapSubscriber._next (mergeMap.js:36)
    at MergeMapSubscriber.next (Subscriber.js:49)
    at Observable._subscribe (subscribeToArray.js:3)
    at Observable._trySubscribe (Observable.js:42)
    at Observable.subscribe (Observable.js:28)
    at MergeMapOperator.call (mergeMap.js:21)`

Seems like the error is related to picker that we use.

Any reason or any missing dependencies?

**Comment by h2qutc** [comment]
@damnForums  A new version **4.0.3** of @angular-material-components/datetime-picker has already been released.
Can you try it ? This version works well with Angular 10.1.1 and Angular Material 10.2.0.
