### ISSUE TITLE
ColorPicker default value

### ISSUE THREAD

**Issue by alekplay** [h2qutc/angular-material-components#112]
When I use the color picker in a reactive form and pass in a default value in hex format I get the following error: 

```
TypeError: c.toHexString is not a function.
```

Code excerpt:

`.ts:`
```
formGroup = this.formBuilder.group({color: '#ffffff'});
```

`.html:`
```
<form [formGroup]="formGroup">
  <mat-form-field>
    <mat-label>Color</mat-label>
    <input matInput [ngxMatColorPicker]="picker"  name="color" id="color" formControlName="color">
    <ngx-mat-color-toggle matSuffix [for]="picker"></ngx-mat-color-toggle>
    <ngx-mat-color-picker #picker></ngx-mat-color-picker>
  </mat-form-field>
</form>
```

Any idea why or how to resolve this?

**Comment by h2qutc** [comment]
@alekplay The type of value provided by colorpicker-component is **Color** that can be imported from **@angular-material-components/color-picker**.
For your example, you can do: 
`
import { Color } from '@angular-material-components/color-picker';
`
`...`
`
formGroup = this.formBuilder.group({color: new Color(255, 243, 0)});
`

**Comment by alekplay** [comment]
Thanks, fwiw this might be worth including in the documentation as I don't believe it currently is. Furthermore it'd be nice if `Color` could accept hex initialization values as well.

**Comment by adubovikov** [comment]
@alekplay 
```
const { r, g, b, a } = stringInputToObject(ipobj.color.font);
 new Color(r, g, b, a);

````
