### ISSUE TITLE
I don't can use MomentDateAdapter

### ISSUE THREAD

**Issue by romik280** [h2qutc/angular-material-components#113]
When I use MomentDateAdapter I get error: this._dateAdapter.getHour is not a function. 

![image](https://user-images.githubusercontent.com/7859604/92927160-d7489380-f445-11ea-95a5-3bc5e0f8a3b7.png)
![image](https://user-images.githubusercontent.com/7859604/92927113-c6981d80-f445-11ea-8582-be7b6b3b0892.png)

**Comment by romik280** [comment]
I found a solution. You need to create an extension class for MomentDateAdapter and  implement methods from NgxMatDateAdapter:
`export class MomentExtendDateAdapter extends MomentDateAdapter {
    getHour(date: moment.Moment): number {
        return date.hours();
    }

    getMinute(date: moment.Moment): number {
        return date.minutes();
    }

    getSecond(date: moment.Moment): number {
        return date.seconds();
    }

    setHour(date: moment.Moment, value: number): void {
        date.hours(value);
    }

    setMinute(date: moment.Moment, value: number): void {
        date.minutes(value);
    }

    setSecond(date: moment.Moment, value: number): void {
        date.seconds(value);
    }

    copyTime(toDate: moment.Moment, fromDate: moment.Moment): void {
        this.setHour(toDate, this.getHour(fromDate));
        this.setMinute(toDate, this.getMinute(fromDate));
        this.setSecond(toDate, this.getSecond(fromDate));
    }

    setTimeByDefaultValues(date: moment.Moment, defaultTime: number[]): void {
        if (!Array.isArray(defaultTime)) {
            throw Error('@Input DefaultTime should be an array');
        }
        this.setHour(date, defaultTime[0] || 0);
        this.setMinute(date, defaultTime[1] || 0);
        this.setSecond(date, defaultTime[2] || 0);
    }

    compareDateWithTime(first: moment.Moment, second: moment.Moment, showSeconds?: boolean): number {
        let res = super.compareDate(first, second) ||
            this.getHour(first) - this.getHour(second) ||
            this.getMinute(first) - this.getMinute(second);
        if (showSeconds) {
            res = res || this.getSecond(first) - this.getSecond(second);
        }
        return res;
    }

    isSameTime(a: moment.Moment, b: moment.Moment): boolean {
        if (a == null || b == null) {
            return true;
        }
        return this.getHour(a) === this.getHour(b)
            && this.getMinute(a) === this.getMinute(b)
            && this.getSecond(a) === this.getSecond(b);
    }
}`

**Comment by h2qutc** [comment]
@romik280  There is already a module **NgxMatMomentModule ** provided by [@angular-material-components/moment-adapter](https://www.npmjs.com/package/@angular-material-components/moment-adapter)
Here is a [demo](https://stackblitz.com/edit/demo-ngx-mat-datetime-picker-angular10)

**Comment by romik280** [comment]
> @ romik280 Уже существует модуль **NgxMatMomentModule,** предоставленный [@ angular-material-components / moment-adapter.](https://www.npmjs.com/package/@angular-material-components/moment-adapter)
> Вы можете проверить эту [демонстрацию](https://stackblitz.com/edit/demo-ngx-mat-datetime-picker-angular10) .

It didn't work for me.
![image](https://user-images.githubusercontent.com/7859604/93057224-3e4c8f00-f676-11ea-8432-207c31231baf.png)

**Comment by romik280** [comment]
> @romik280 There is already a module **NgxMatMomentModule** provided by [@angular-material-components/moment-adapter](https://www.npmjs.com/package/@angular-material-components/moment-adapter)
> You can check this [demo](https://stackblitz.com/edit/demo-ngx-mat-datetime-picker-angular10) out.

It didn't work for me.
![93057224-3e4c8f00-f676-11ea-8432-207c31231baf](https://user-images.githubusercontent.com/7859604/93061600-7525a380-f67c-11ea-8996-3cd3e86c58db.png)

**Comment by biel-correa** [comment]
had the same issue after creating a form group, my solution was to convert the date to a moment  Ex: `moment.Moment(date)`
