### ISSUE TITLE
ngx-mat-color-picker onChange event 

### ISSUE THREAD

**Issue by SashaMalahov** [h2qutc/angular-material-components#119]
Hi,

I want to use ngx-mat-color-picker as described here:
https://github.com/h2qutc/angular-material-components#color-picker
https://stackblitz.com/edit/demo-ngx-mat-color-picker

Does ngx-mat-color-picker has any event like onChange/onColorChange so I can handle this event on .ts side?

**Comment by h2qutc** [comment]
@SashaMalahov  You can do like that: 

`  @ViewChild('picker', {static: true}) colorPicker: NgxMatColorPickerComponent;
`

`
ngOnInit() {this.colorPicker._selectedChanged.subscribe(val => {console.log('colorPicker changed', val)}) }
`

**Comment by SashaMalahov** [comment]
Thanks @h2qutc ! It works
I was also able to do this by subscribing to form control value changes

**Comment by seiyria** [comment]
This is an awful lot of boilerplate for something that could be an output :/ If someone were to PR this, would you accept it?

**Comment by LeonardoRick** [comment]
Hi, this feature would be really helpfull. I would love to know why an output was never implemented previously. Thanks!
