### ISSUE TITLE
4.x version with angular 10,  provided 'undefined' where a stream was expected

### ISSUE THREAD

**Issue by EsilvGuillaume** [h2qutc/angular-material-components#126]
Hi,

Since i upgraded my release to 4.xx, with angular 10 migration, i had this error in all my component with ngx-mat-datetime-picker.
I saw that this bug was report in other ticket but it seems it was fixed. But i have always this bug. 
The component works well, it's just an exception that appear in console.

ERROR TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at subscribeTo (subscribeTo.js:27)
    at subscribeToResult (subscribeToResult.js:11)
    at MergeMapSubscriber._innerSub (mergeMap.js:59)
    at MergeMapSubscriber._tryNext (mergeMap.js:53)
    at MergeMapSubscriber._next (mergeMap.js:36)
    at MergeMapSubscriber.next (Subscriber.js:49)
    at Observable._subscribe (subscribeToArray.js:3)
    at Observable._trySubscribe (Observable.js:42)
    at Observable.subscribe (Observable.js:28)
    at MergeMapOperator.call (mergeMap.js:21)

Thanks for ur work

**Comment by h2qutc** [comment]
@EsilvGuillaume Hi, which version of Angular + Angular-Material you used plz ?

**Comment by MaryJJ** [comment]
Hi, I have the same error
    "@angular-material-components/datetime-picker": "^4.0.5",
    "@angular/animations": "~10.0.11",
    "@angular/cdk": "^10.1.3",
    "@angular/common": "~10.0.11",
    "@angular/compiler": "~10.0.11",
    "@angular/core": "~10.0.11",
    "@angular/flex-layout": "^10.0.0-beta.32",
    "@angular/forms": "~10.0.11",
    "@angular/material": "^10.1.3",
    "@angular/platform-browser": "~10.0.11",
    "@angular/platform-browser-dynamic": "~10.0.11",
    "@angular/router": "~10.0.11"

**Comment by EsilvGuillaume** [comment]
i fixed it, my dependency of angular and material was 10.0.0 instead of 10.2.1 for angular and 10.1.2 for material.

Sorry for waste ur time
