### ISSUE TITLE
Timepicker not showing any number 

### ISSUE THREAD

**Issue by sanjaykumarpushadapu** [h2qutc/angular-material-components#133]
I am using angular 10.1.5. Timepicker not showing any number  and up and key arrow also not working .
when i was clicking down or up arrow time not changing .

html code:- 
<ngx-mat-timepicker [(ngModel)]="date" > </ngx-mat-timepicker>

ts code :-
  public date: moment.Moment;

![timepicker](https://user-images.githubusercontent.com/22410141/96135158-13758500-0f19-11eb-8b71-0c2a07bbc40b.PNG)

**Comment by h2qutc** [comment]
@sanjaykumarpushadapu  If you use the Moment.js, you should have imported the NgxMatMomentModule. I close the issue, if the bug is still there, feel free to reopen it please.
