### ISSUE TITLE
Output events when datetime picket has been closed.

### ISSUE THREAD

**Issue by YadavAvinashK** [h2qutc/angular-material-components#136]
What is the way to handle calendar control values once the calendar is closed by either way? Is there some events like "closedStream" as in mat datepicker?

**Comment by h2qutc** [comment]
@YadavAvinashK the events **closedStream** and **openedStream** are available as in mat datepicker. 
You can do like that: 

`  @ViewChild('picker', {static: true}) picker: any;
`

`
ngOnInit() {
    this.picker.closedStream.subscribe(() => {
      console.log('closed');
    })
    this.picker.openedStream.subscribe(() => {
      console.log('opened');
    })  
  }
`
