### ISSUE TITLE
Time is barely visible when "fill" appearance value is provided by default

### ISSUE THREAD

**Issue by IslombekMe** [h2qutc/angular-material-components#138]
Version: 4.0.5
Angular: 10.2.1

My parent module provides the `MAT_FORM_FIELD_DEFAULT_OPTIONS` token with `fill` appearance. When this is provided, all of the mat-form-fields inherit this in their appearance, including fields inside this library's `timepicker`. When this happens, unfortunately the time can't really be seen.

![image](https://user-images.githubusercontent.com/33321034/97797554-e7a80e00-1c3f-11eb-96e2-26d432793679.png)

What could be done to solve this is to give the mat-form-fields inside `timepicker` an explicit `appearance` value. From what I understood, `appearance="legacy"` should fix this.
```html
<mat-form-field appearance="legacy">
  <input formControlName="hour">
</mat-form-field>
```

**Comment by IslombekMe** [comment]
Turns out that's because `appearance="file"` adds padding to form-field. 
the following code in a global (not component) css file temporarily fixes the issue:
```css
ngx-mat-timepicker .mat-form-field-flex {
  padding: 0 !important
}
```

**Comment by h2qutc** [comment]
Please check the latest version (4.X for Angular 10, 5.x for Angular 11) to resolve the problem.
Thanks all for your supports.
