### ISSUE TITLE
NgxMatDatetimePicker<any> is not assignable to type MatDatepickerBase

### ISSUE THREAD

**Issue by RGVGreatCoder** [h2qutc/angular-material-components#140]
Today I created a new Angular project using **Angular 11.0.0**. I then installed `@angular-material-components/datetime-picker` and this part of what reads in my package.json file:

```
...
"@angular/core": "~11.0.0",
"@angular/material": "^11.0.0",
"@angular/animations": "~11.0.0",
...
"@angular-material-components/datetime-picker": "^4.0.5",
...
```

All my code works well except in my HTML where I define `mat-datepicker-toggle` referring to `ngx-mat-datetime-picker`. I get the following error:

`error TS2322: Type 'NgxMatDatetimePicker<any>' is not assignable to type 'MatDatepickerBase<MatDatepickerControl<any>, any, any>'.`

Here is my HTML code:

```
<input matInput [ngxMatDatetimePicker]="picker" placeholder="Choose a date"
         formControlName="scheduledStartDateTime" 
         [min]="minDate" 
         (dateChange)="dateUpdated()" >
<mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
<ngx-mat-datetime-picker #picker [showSpinners]="true" [showSeconds]="false"
                           [stepHour]="1" [stepMinute]="1" [stepSecond]="1"
                           [touchUi]="false" [enableMeridian]="false"
                           [disableMinute]="false" [hideTime]="false">
</ngx-mat-datetime-picker>
```

I can disable Angular from flagging this validation error (and have my project run fine) by changing this property in the **tsconfig.json** file:
```
"angularCompilerOptions": {
    ...
    "strictTemplates": false
}
```
However, I would like to have the validation benefits by having `"strictTemplates": true`. 

Am I missing something or can you guys please let me know when this bug gets fixed?

**Comment by nspire909** [comment]
Temporary solution:

From [https://angular.io/guide/template-typecheck](https://angular.io/guide/template-typecheck):
Use the $any() type-cast function in certain contexts to opt out of type-checking for a part of the expression

So change your toggle element to:
`<mat-datepicker-toggle matSuffix [for]="$any(picker)"></mat-datepicker-toggle>`

A fix to support strict type checking would require one of the following changes to the library:
Make `NgxMatDatetimePicker` extend `MatDatepickerBase` like `MatDatepicker` does.
or
Create a new component to replace the usage of the `mat-datepicker-toggle` component by this library, eg `ngx-mat-datetime-picker-toggle`.

**Comment by h2qutc** [comment]
@RGVGreatCoder  A new version **v5.0.0** of [@angular-material-components/datetime-picker](https://www.npmjs.com/package/@angular-material-components/datetime-picker) has been released for Angular 11. 
Can you check it out ? 
I will close the issue. If the bug is not resolved with the version 5.x, feel free to reopen.

**Comment by nspire909** [comment]
This is still broken if you are using strictTemplates. As I mentioned you can use the `$any()` cast to ignore the type mismatch, but a better solution would be to either have `NgxMatDatetimePicker` extend `MatDatepickerBase` or create a new component to replace the usage of the `mat-datepicker-toggle` component, where its [for] parameter would be of type `NgxMatDatetimePicker`.

**Comment by VashJuan** [comment]
See https://stackoverflow.com/questions/64826483/ngxmatdatetimepicker-is-not-assignable-to-type-matdatepickerbase for details about how to add the $any() cast...
