### ISSUE TITLE
Upgrade to Angular 11

### ISSUE THREAD

**Issue by MDzyga** [h2qutc/angular-material-components#142]
Hi,
Please update all components to the latest version of Angular.
Thanks

**Comment by josepfdc** [comment]
👍

**Comment by josepfdc** [comment]
> Hi,
> Please update all components to the latest version of Angular.
> Thanks

👍

**Comment by Mokette** [comment]
Hello ! 
Just a question, i haven't upgrade angular yet, was waiting for a release of angular-marterial-component to a version with angular11 compatibility.
Is someone has already upgrade angular to version 11, is angular-material-component only throw warning for peer dependencies to angular10 ? or is angular-material-component totaly not working with angular 11 ?
Thanks.

Regards,

**Comment by MDzyga** [comment]
Yes, I upgraded and it works but you have a lot of warnings.

**Comment by Mokette** [comment]
Ok thanks for your anwser !
Hope @h2qutc will build a release for angular 11 compatibility soon when he got time to do it :)

**Comment by h2qutc** [comment]
Hi all (@Mokette, @MDzyga ...), a new version **v5.0.0** of [@angular-material-components/datetime-picker](https://www.npmjs.com/package/@angular-material-components/datetime-picker) has already been released for Angular 11 / Angular Material 11.
Feel free to check it out. Thanks all for your support.

**Comment by Mokette** [comment]
Yes Thanks you @h2qutc :)
Works well !
Would you mind to also upgrade the moment-adapter please ;)

Regards
