### ISSUE TITLE
DateTimePicker Feat: 24:00:00 support (= tomorrow midnight)

### ISSUE THREAD

**Issue by f-aubert** [h2qutc/angular-material-components#145]
The component is pretty cool, but lack support for "tomorrow" midnight.
In a 24h setup, support the input of time 24:00:00 in the time section to mean tomorrow midnight.
2020-11-18, 24:00:00 = 2020-11-19, 00:00:00

**Comment by h2qutc** [comment]
@f-aubert The input of time is displayed by using [Intl.DateTimeFormat](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Intl/DateTimeFormat) if you are using NativeDateModule. You can customize your date formats by providing a custom NGX_MAT_DATE_FORMATS. 

```
const DEFAULT_DATE_INPUT = {
  year: 'numeric', month: 'numeric', day: 'numeric',
  hourCycle: 'h23', hour: "2-digit", minute: "2-digit", second: "2-digit"
}
export const CUSTOM_DATE_FORMATS : NgxMatDateFormats = {
  parse: {
    dateInput: DEFAULT_DATE_INPUT,
  },
  display: {
    dateInput: DEFAULT_DATE_INPUT,
    monthYearLabel: { year: 'numeric', month: 'short' },
    dateA11yLabel: { year: 'numeric', month: 'long', day: 'numeric' },
    monthYearA11yLabel: { year: 'numeric', month: 'long' },
  }
};
...

@NgModule({
  imports: [
    CommonModule,
    ...
  ],
  providers: [
    { provide: NGX_MAT_DATE_FORMATS, useValue: CUSTOM_DATE_FORMATS }
  ]
})
```
The property **hourCycle** is for your needs.

**Comment by f-aubert** [comment]
Thank you for answering. I wasn't able to make it work yet with the Moment Adapter. Still working on it.

**Comment by f-aubert** [comment]
Here you see my DateTimePicker configured with 'DD.MM.YYYY, kk:mm:ss'
![Capture](https://user-images.githubusercontent.com/17121187/112598091-5fa0eb80-8e0e-11eb-90e2-0370816ba7af.PNG)
I would like to both
1) select March 25 with time 24:00:00 (currently the hour spinner range only from 0 to 23), and have it interpreted as March 26 at 00:00:00=midgnight at start of day (possibly with a custom datetimeadapter).
2) write in the input field 25.03.2021, 24:00:00 and also have it interpred as March 26 at 00:00:00=midnight at start of day
3) ideally 24:00:01 should not be allowed either with spinner or manually
