### ISSUE TITLE
Disable minute and seconds in timepicker

### ISSUE THREAD

**Issue by filipeglfw** [h2qutc/angular-material-components#15]
Allow us to disable input/change in the minute and seconds in time picker.

Use case: I have hourly KPIs, so I only wanted users to be able to search for a date with round hours.
I can do that manipulating the value after the it is changed but this is not the optimum UX.

Thanks

**Comment by h2qutc** [comment]
Hi, This issue is now fixed in the version [**v2.0.2**](https://www.npmjs.com/package/@angular-material-components/datetime-picker). Feel free to check it out ^.^
You can disable minute in time picker by using input **disableMinute**. 
To disable seconds, you can use the input **showSeconds**.

**Comment by filipeglfw** [comment]
Perfect!
