### ISSUE TITLE
Update to support latest angular 11 please

### ISSUE THREAD

**Issue by sortel64** [h2qutc/angular-material-components#160]
Package "@angular-material-components/datetime-picker" has an incompatible peer dependency to "@angular/cdk" (requires "~10.2.2", would install "11.0.3").

Also, I'm not sure what this warning is when this library is compiled:
`Warning: Unable to fully load /home/sortel/git/smcentral/core-ui/src/main/ngapp/node_modules/@angular-material-components/datetime-picker/lib/timepicker.module.d.ts for source-map flattening: Circular source file mapping dependency: /home/sortel/git/smcentral/core-ui/src/main/ngapp/node_modules/@angular-material-components/datetime-picker/lib/timepicker.module.d.ts.map -> /home/sortel/git/smcentral/core-ui/src/main/ngapp/node_modules/@angular-material-components/datetime-picker/lib/timepicker.module.d.ts.map
`

Thanks for a great component!!

**Comment by h2qutc** [comment]
Hi @sortel64 , 
Please check **@angular-material-components/datetime-picker v5.1.0**  that is compatible with Angular 11.1.x or above.
Thanks,
