### ISSUE TITLE
Questions: Possible to hide the seconds in the display and disable manual input?

### ISSUE THREAD

**Issue by MatthewLHolden** [h2qutc/angular-material-components#194]
1. Is it possible to hide the seconds from the displayed date / time format? I've hidden it from selection when selecting a date, but I'd also like to not display it in the input field too

<img width="208" alt="Screenshot 2021-05-11 at 14 17 56" src="https://user-images.githubusercontent.com/22961324/117821686-bd28b480-b263-11eb-8466-d9fec44c2afd.png">

2. Is it possible to disable manual input and prevent a user from typing in the input field?

Thanks all

**Comment by jocelynlecomte** [comment]
For your first question, check the README under the "Choosing a date implementation and date format settings" section.
The idea is that you create a custom format (the `parse.dateInput` and `display.dateInput` parts are the most relevant to your problem) which does not display the seconds.

**Comment by abelespana** [comment]
Hi, for your second question, adding an attribute "readonly" to the native html input element will do the job

Here's mine:

```
          <mat-form-field appearance="outline">
            <input 
              matInput
              readonly <!-- Add this to the input html native element so the user can't write with the keyboard -->
              [ngxMatDatetimePicker]="picker" 
              placeholder="{{ 'COMMON.SELECT' | translate }}"
              [formControl]="dateControl">
            <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
            <ngx-mat-datetime-picker 
              #picker 
              [showSpinners]="true" 
              [showSeconds]="false" 
              [stepHour]="1"
              [stepMinute]="1" 
              [stepSecond]="1" 
              [touchUi]="false" 
              [enableMeridian]="false" 
              [disableMinute]="false" 
              [hideTime]="false">
              <ng-template>
                <span>{{ 'COMMON.SEARCH' | translate }}</span>
              </ng-template>
            </ngx-mat-datetime-picker>
          </mat-form-field>
```

**Comment by MatthewLHolden** [comment]
Thanks @abelespana !
