### ISSUE TITLE
Not able to get the change event or event when we choose the date time

### ISSUE THREAD

**Issue by manuradisys** [h2qutc/angular-material-components#209]
Requirement is to show alert on choosing a particular date and time and i am not able to find a event emitter from the library.
Kindly assist me on this

**Comment by h2qutc** [comment]
@manuradisys  You can listen these Outputs: 

dateChange:  Emits when a change event is fired on this <input>.

dateInput:  Emits when an input event is fired on this <input>.

stateChanges: Emits when the internal state has changed.
