### ISSUE TITLE
Wrong display format

### ISSUE THREAD

**Issue by Mokette** [h2qutc/angular-material-components#22]
Hello !
I use this custom definition of date format to provide MAT_DATE_FORMATS : 
```
export const MY_CUSTOM_MOMENT_FORMATS = {
    parse: {
        dateInput: 'L LT'
    }, 
    display: {
        dateInput: 'L LT',
        monthYearLabel: 'MMMM YYYY',
        dateA11yLabel: 'LL',
        monthYearA11yLabel: 'MMMM-YYYY',
    }
}
```

but since the new update 2.0.3 the date display in my inputs is : hh:mm:ss !
I don't use the `LTS` for the dateInput in my custom format but `LT`i shouldn't have the seconds display in my input (was working well in the 2.0.1 version)

edit: i've notice that the `L` is not taking account correctly for display as `L` but as `l` today we're the 01/04/2020 and the display is 1/4/2020 :/

Thanks for your help :)
If more informations are needed i'll be glad to provide them

Versions use and work fine : 
"@angular-material-components/datetime-picker": "2.0.2",
"@angular-material-components/moment-adapter": "2.0.1"

Versions causing error : 
"@angular-material-components/datetime-picker": "2.0.3",
"@angular-material-components/moment-adapter": "2.0.2",

**Comment by h2qutc** [comment]
Did you provide custom **NGX_MAT_DATE_FORMATS** in your module?  

```
providers: [
    { provide: NGX_MAT_DATE_FORMATS, useValue: CUSTOM_MOMENT_FORMATS }
  ]
```
From version 2.0.3, we would provide NGX_MAT_DATE_FORMATS instead of MAT_DATE_FORMATS.

**Comment by Mokette** [comment]
No i've provied MAT_DATE_FORMATS
```
{
    provide: MAT_DATE_FORMATS,
   useValue: MY_CUSTOM_MOMENT_FORMATS
}
```

i'll try with NGX_MAT_DATE_FORMATS with 2.0.3 version

**Comment by Mokette** [comment]
Yes it works well with providing NGX_MAT_DATE_FORMATS instead of MAT_DATE_FORMATS

Thanks a lot @h2qutc :)

**Comment by Mokette** [comment]
Just one more question @h2qutc , where would I have gotten the information of this change for the relase 2.0.3 ?
Could it be possible to have a changelog (i know it some work to do :s) for each release ?

Regards,

**Comment by h2qutc** [comment]
@Mokette There was a [live demo and documentation here](https://h2qutc.github.io/angular-material-components). You are right ;) I will provide a changelog for each release. It is always useful.
Thanks a lot ^.^

**Comment by Mokette** [comment]
Oh yes i havn't notice that the recommandation for provider had change in the last documentation sorry :s 
Yes it always helps but i know it is also lot of work too ^^
you're welcome :)

Regards,
