### ISSUE TITLE
ng13 version of moment-adapter

### ISSUE THREAD

**Issue by casual-apathy** [h2qutc/angular-material-components#229]
Could we have an ng13 version of moment-adapter? v6.0.0 is dependent on @angular/common@"^12.0.0"

TIA

**Comment by h2qutc** [comment]
Hi, a new version [@angular-material-components/moment-adapter v7.0.0](https://www.npmjs.com/package/@angular-material-components/moment-adapter) supporting angular 13 has been already released.
Feel free to check it out.
