### ISSUE TITLE
Just wanted to say Thanks

### ISSUE THREAD

**Issue by darkedges** [h2qutc/angular-material-components#24]
Been up since 4am because I can't sleep at the moment. Wanted a Date Time Picker, and eventually discovered yours. This is exactly what I wanted to get an idea out of my head.

Thanks once again, as it was driving me nuts that I could not find a solution that looked and worked like yours.

**Comment by h2qutc** [comment]
Hi, I am glad to hear from you 😃. 
Thank you very much 😄
