### ISSUE TITLE
Support for angular 14

### ISSUE THREAD

**Issue by skrtheboss** [h2qutc/angular-material-components#274]
```
warning " > @angular-material-components/datetime-picker@7.0.1" has incorrect peer dependency "@angular/platform-browser@^13.0.1".
warning " > @angular-material-components/datetime-picker@7.0.1" has incorrect peer dependency "@angular/common@^13.0.1".
warning " > @angular-material-components/datetime-picker@7.0.1" has incorrect peer dependency "@angular/core@^13.0.1".
warning " > @angular-material-components/datetime-picker@7.0.1" has incorrect peer dependency "@angular/forms@^13.0.1".
warning " > @angular-material-components/datetime-picker@7.0.1" has incorrect peer dependency "@angular/material@^13.0.1".
warning " > @angular-material-components/datetime-picker@7.0.1" has incorrect peer dependency "@angular/cdk@^13.0.1".
warning " > @angular-material-components/moment-adapter@7.0.0" has incorrect peer dependency "@angular/common@^13.0.1".
warning " > @angular-material-components/moment-adapter@7.0.0" has incorrect peer dependency "@angular/core@^13.0.1".

```

**Comment by Mokette** [comment]
Hello :)

Any news on when the PR will be accepted to support angular 14 ? 

Regards

**Comment by marinus-suniram** [comment]
Any update on this?

**Comment by asatryanarsen** [comment]
Hi everyone, I appreciate the amount of work that has been done on this library. 

I just want to check if there is a blocker for this to happen or smith that we can help with to push this project to be compatible angular 14 version?

**Comment by h2qutc** [comment]
Hi all, sorry for the late reply. A new version supporting Angular 14 will be released within 2 days. 
Thanks all for your support

**Comment by bogdandevlpr** [comment]
Any news on the update for angular 14 ?

**Comment by John-Santacruz** [comment]
Hello, please release the update for angular 14

**Comment by alexciesielski** [comment]
4 days later

**Comment by prosidney** [comment]
+1

**Comment by MathewBerg** [comment]
TSickle was just updated and I also updated my PR and the build is now passing. @h2qutc you're more then welcome to take my pr.

**Comment by h2qutc** [comment]
Hi all, 
The new version v8.0.0 supporting Angular 14 has been released. Feel free to check it out.
Thank you for your support.
