### ISSUE TITLE
Support for Angular 15

### ISSUE THREAD

**Issue by vitiok123** [h2qutc/angular-material-components#296]
Package "@angular-material-components/datetime-picker" has an incompatible peer dependency to "@angular/cdk" (requires"^14.0.1", would install "15.0.0").
Package "@angular-material-components/datetime-picker" has an incompatible peer dependency to "@angular/material" (requires "^14.0.1", would install "15.0.0").

**Comment by h2qutc** [comment]
@vitiok123  Can you check this issue plz ? https://github.com/h2qutc/angular-material-components/issues/299
