### ISSUE TITLE
Angular 15 support

### ISSUE THREAD

**Issue by RomainTHD** [h2qutc/angular-material-components#299]
Do you have any plans for Angular 15 support, since this repo hasn't been updated for over 2 years?
Or is the project discontinued?

Thanks 😊 

(I know this is a duplicate of #296)

**Comment by h2qutc** [comment]
@RomainTHD  Yes of course, Angular 15 will be supported. Hope that a new version with Angular 15 will be released in this week.

**Comment by RomainTHD** [comment]
Perfect, thanks!

**Comment by proggler23** [comment]
@h2qutc any forecast, if it will be possible this week/starting next week? :)

PS: thanks for the great work, dude!

**Comment by wilson3q** [comment]
Any update on this?

**Comment by proggler23** [comment]
> @RomainTHD Yes of course, Angular 15 will be supported. I will try to release a new version with Angular 15 in this week.

i'm fine if it turned out to take longer as well, but i would need the info, if you plan to acchieve it this week, or later :)

**Comment by robertwbuchmann** [comment]
Just to add some friendly pressure here :) 

Thanks for the great work!

**Comment by h2qutc** [comment]
hi all, sorry about the late reply. Too busy with World Cup. I'm upgrading with Angular 15. I try my best to release on this Friday 💯

**Comment by robertwbuchmann** [comment]
No rush h2qutc! You're awesome. I bought you some coffees :)

**Comment by jwrascoe** [comment]
@h2qutc FANTASTIC!!!  Thank you for working on this.

**Comment by francisco-salesbuildr** [comment]
@h2qutc Is it possible to you provide any status about the support angular 15?

**Comment by h2qutc** [comment]
Hi all, a version **v9.0.0** has been already released with support Angular 15 (https://www.npmjs.com/package/@angular-material-components/datetime-picker?activeTab=versions). 
There will be certainly the issues, check it out and let me know if it works as expected. 
Thank you all for your support.

**Comment by Jens1977** [comment]
thanks for the update! I've noticed styling has changed (somewhat dramatically). Is there some way I can override the new styling with the 'old' one?

**Comment by proggler23** [comment]
If your application uses the legacy material components, then also the datetime picker still looks the same ;)

**Comment by Jens1977** [comment]
Okay, but what if I don't? I'll have to style the components myself?

**Comment by wilson3q** [comment]
> If your application uses the legacy material components, then also the datetime picker still looks the same ;)

please consider to migrate the components used to mdc version if possible...mdc is the future. thanks.

**Comment by GeorgeKnap** [comment]
After migrating to v9 with material 15 this is how the dialog looks for me 
![image](https://user-images.githubusercontent.com/11920691/208605231-97adb17a-ab48-4c7d-ac35-46e000e472af.png)

any way how to set the size of the dialog?

**Comment by h2qutc** [comment]
Hi all, if you don't use the legacy Angular Material components, please use the version v15.0.0 .(https://www.npmjs.com/package/@angular-material-components/datetime-picker)
