### ISSUE TITLE
Format datetime with optional time

### ISSUE THREAD

**Issue by rscherer** [h2qutc/angular-material-components#31]
Hi, on our application we got a date component that may or may not display and parse time. Because of this setting, we start using this datetime component. We also have some specific date formats that can have time or only date.

I successfully used a date-adapter to format the input, using locale and stuff, and everything is working. Except that since the component is the same, we are using the same _FORMATS_ const. So, my question is, how do I know if the component is using a timepicker input value true or false?

I tried to use different formats, including the default ones, but nothing changed.

I started a stackblitz to demonstrate the problem:
https://stackblitz.com/edit/angular-g2j7kw

We got a **timePicker Input**, and bot components are using the _format()_ on _date-adapter.ts_, I just dont know how to consider the timepicker option (or hideTime from the component), to format it with or without time.

Any advices or suggestions? Thanks :)

**Comment by h2qutc** [comment]
Hi, 
Sorry for late reply. In your [demo stackblitz](https://stackblitz.com/edit/angular-g2j7kw?file=src%2Fapp%2Fdate-time%2Fdatetime.component.ts)  Why don't you create two seperated components instead of a component avec **@input timepicker**, then you can define for each components a provider. You could use useFactory in this case.

**Comment by rscherer** [comment]
Hi! Thanks for your answer. That's exactly what I did to solve the problem, and it's all working fine right now. I opened this issues just to see if there's a more 'official' way to do that, or if I was missing something. For now, I will close the issue as it is not a problem or necessary.

Anyway, thanks again, for your answer and for the library itself! Great job! :)
