### ISSUE TITLE
Angular Material 15 support

### ISSUE THREAD

**Issue by spnikit** [h2qutc/angular-material-components#316]
Hello. Are there any plans to support version 15 of material? As currently Datepicker almost all broken visually.

**Comment by AlexElin** [comment]
@spnikit could you provide screenshots which display what is broken?

**Comment by docaohuynh** [comment]
@spnikit Use v9.0.0 works with angular 15

**Comment by r-gruber** [comment]
@docaohuynh I tried 9.0.0 but it does not work with Angular 15 (at least the file-input, which I would need, does not work).
@AlexElin here is a very simple example https://stackblitz.com/edit/angular-wgdltk

![image](https://user-images.githubusercontent.com/21007593/226058688-00af56cd-bcff-4b6a-87d5-127ef2074522.png)
This is how the file-input component looks in Angular 15. The input field looks like it is rendered as a plain old HTML input, the file sector icon is half outside of the form field.

**Comment by clampinou** [comment]
@docaohuynh same problem here :(

**Comment by dhruvi175** [comment]
Facing same issue

**Comment by marcellomaia** [comment]
I'm having the same issues with file-input.  The problem is with angular material 15 and 16. It's using the old material (mat-input-element, mat-form-field-autofill-control etc) classes and not the MDC (mat-mdc-input-element, etc) ones so it's not styled correctly.  Any chance of having a version compatible with angular material 15/16?

**Comment by spinstron** [comment]
I'm also facing same issue....
![Screenshot 2023-06-13 171442](https://github.com/h2qutc/angular-material-components/assets/124863502/1d351717-7ed2-4f02-8134-0be0973fff74)

**Comment by ioanbin** [comment]
Hello, there is also another issue, when this picker co-exists with the official date picker from the material! Are re there any news regarding this topic? 
![image](https://github.com/h2qutc/angular-material-components/assets/88321873/2242047e-c394-434e-b529-744d71f53e50)

**Comment by h2qutc** [comment]
Hi all, if you don't use the legacy Angular Material components, please use the version v15.0.0 .(https://www.npmjs.com/package/@angular-material-components/datetime-picker)

**Comment by r-gruber** [comment]
> ![image](https://user-images.githubusercontent.com/21007593/226058688-00af56cd-bcff-4b6a-87d5-127ef2074522.png) This is how the file-input component looks in Angular 15. The input field looks like it is rendered as a plain old HTML input, the file sector icon is half outside of the form field.

@h2qutc I just updated my very very simple example from above to the v15.0.0 of the file-input. It is still visually broken:
https://stackblitz.com/edit/angular-jxsvsh
![image](https://github.com/h2qutc/angular-material-components/assets/21007593/2847947e-da4d-4cd9-8b1e-c95b9db16a06)
