### ISSUE TITLE
Angular 16 compatibility

### ISSUE THREAD

**Issue by fabian-laine** [h2qutc/angular-material-components#324]
Is it compatible with angular 16?

**Comment by json-derulo** [comment]
I'm getting peer dependency errors during install, because the peer dependencies to the Angular packages are defined as `^15.0.1`.

**Comment by goblinss** [comment]
A log of nom install command

npm ERR! While resolving: @angular-material-components/color-picker@9.0.0
npm ERR! Found: @angular/cdk@16.0.0
npm ERR! node_modules/@angular/cdk
npm ERR!   @angular/cdk@"^16.0.0" from the root project
npm ERR!   peer @angular/cdk@"16.0.0" from @angular/material@16.0.0
npm ERR!   node_modules/@angular/material
npm ERR!     @angular/material@"^16.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/cdk@"^15.0.1" from @angular-material-components/color-picker@9.0.0
npm ERR! node_modules/@angular-material-components/color-picker
npm ERR!   @angular-material-components/color-picker@"^9.0.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @angular/cdk@15.2.9
npm ERR! node_modules/@angular/cdk
npm ERR!   peer @angular/cdk@"^15.0.1" from @angular-material-components/color-picker@9.0.0
npm ERR!   node_modules/@angular-material-components/color-picker
npm ERR!     @angular-material-components/color-picker@"^9.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by alsami** [comment]
You need any help with this? I am willing to send a PR. I saidly cannot find the actual sources, this repository is outdated (last commit 2022)

**Comment by gadipati** [comment]
file-input is not working with --force.

**Comment by John-Santacruz** [comment]
Please release the version that is compatible with angular v16

**Comment by Schloesslin** [comment]
When will it be released please ?

**Comment by lucas-macori** [comment]
Installing with --force works, but it would be nice to have a Angular16 compatible version to avoid using it

**Comment by goblinss** [comment]
<img width="952" alt="2023-06-20 19 41 30" src="https://github.com/h2qutc/angular-material-components/assets/28497604/e1feae7b-7ba4-43e5-b283-8054fb98b148">

https://github.com/h2qutc/angular-material-components/pull/325#issuecomment-1598497689

**Comment by Startouf** [comment]
Hi @goblinss, any news regarding Angular 16 compatibility ?

**Comment by SERGEES** [comment]
any updates on 16?

**Comment by roma2341** [comment]
Added Angular 16 package to NPM as a temporary solution
https://www.npmjs.com/package/angular-material-components-zigzag-datetime-picker

**Comment by stephanrauh** [comment]
@roma2341 Can you add the link to your GitHub repository, please?

**Comment by h2qutc** [comment]
Hi all, a version v16.0.0 has been already released with support Angular 16 (https://www.npmjs.com/package/@angular-material-components/datetime-picker?activeTab=versions).
There will be certainly the issues, check it out and let me know if it works as expected.
Thank you all for your support.

**Comment by roma2341** [comment]
> 

I think i did something wrong, because i just took angular 15 branch and added 3 commits, i have never contributed to opensource, so i don't know how it works.
