### ISSUE TITLE
SvgIcon - ColorToggleComponent

### ISSUE THREAD

**Issue by vakulamariann** [h2qutc/angular-material-components#339]
The ColorPicker right now is using a Material Design icon called 'palette' in the [color-toggle.component.html ](https://github.com/h2qutc/angular-material-components/blob/0d8a59fd4692dd83bff2f6bc723ffb3bacb4e8cd/projects/color-picker/src/lib/components/color-toggle/color-toggle.component.html)

Sometimes the developers can not use the Material Design icons or simply they want to customize the icon, so it would be good the make it possible to use svgIcons instead.

**Comment by h2qutc** [comment]
@vakulamariann  You are right. I will try to release new version supporting custom buttons within 2 days.

**Comment by h2qutc** [comment]
@vakulamariann A new version v16.0.1 supporting custom button toggle has been released. Feel free to check it out https://h2qutc.github.io/angular-material-components/#/datetimepicker

**Comment by vakulamariann** [comment]
@h2qutc Thank you so much for you quick solution! Is it possible to backport this feature to 7.x version too?
