### ISSUE TITLE
Spinner icons are not loading

### ISSUE THREAD

**Issue by ghost** [h2qutc/angular-material-components#377]
<img width="1228" alt="Screenshot 2024-01-05 at 2 07 06 PM" src="https://github.com/h2qutc/angular-material-components/assets/108806018/e4735614-4e94-4cda-96a8-f83b7b2d0017">

**Comment by Ravipatel1309** [comment]
You have to add Material icons in your index.html

Link for Material icons:
`<link href="https://fonts.googleapis.com/icon?family=Material+Icons&display=block" rel="stylesheet">`

It is mentioned in their readme itself
[Themes for DateTime picker](https://www.npmjs.com/package/@angular-material-components/datetime-picker#theming)

**Comment by ghost** [comment]
Thanks @Ravipatel1309
