### ISSUE TITLE
Closing picker window on custom event 

### ISSUE THREAD

**Issue by klimtron** [h2qutc/angular-material-components#38]
Hello, I'm trying to close datepicker windows while switching between active form rows on custom event without success Maybe someone could help me.
HTML:
```
<mat-form-field>
    <input class="datePicker startDate" name="startDate" matInput
        [ngxMatDatetimePicker]="startDate" placeholder="" formControlName="startDate"
        (dateChange)="changeDate('startDate', $event, reservationIndex)" [min]="minDate"
        [max]="maxDate" [readonly]="true" (click)="startDate.open()">
    <mat-datepicker-toggle matSuffix [for]="startDate"></mat-datepicker-toggle>
    <ngx-mat-datetime-picker #startDate [disableSecond]="true"></ngx-mat-datetime-picker>
    <mat-error>
        <div class="validation-error"
            *ngIf="!startDateControl(reservationIndex).valid && startDateControl(reservationIndex).touched">
            Błędny czas rozpoczęcia</div>
        <div *ngIf="selectedRowIndex === reservationIndex">
            <div class="validation-errors"
                *ngFor="let error of errorAPIError; let i=index">
                <div *ngFor="let field of error.fields; let iF=index">
                    <div *ngIf="field === 'startDate'">
                        <span>API: {{error.message}}</span>
                    </div>
                </div>
            </div>
        </div>
    </mat-error>
</mat-form-field>
```

form.component.ts:
```
@ViewChild('startDate',{static: false}) public startDatePicker: MatDatepicker<any>;
@ViewChild('endDate',{static: false}) public endDatePicker: MatDatepicker<any>;
```

```
switchRowIndex(index: number) {
this.startDatePicker.close();
this.endDatePicker.close();
}
```

Regards

**Comment by h2qutc** [comment]
Hi, 
Did you try that ?
```
@ViewChild('startDate',{static: false}) public startDatePicker: NgxMatDatetimePicker<any>;
@ViewChild('endDate',{static: false}) public endDatePicker: NgxMatDatetimePicker<any>;
```
The type of picker is NgxMatDatetimePicker, not MatDatepicker.

**Comment by klimtron** [comment]
Hi, when I'm trying to add NgxMatDatetimePicker, I receive: "Cannot find name 'NgxMatDatetimePicker'", which is quite strange because I'm using it in this class of FormComponent.
Inside my app.module I've got:
`import { NgxMatDatetimePickerModule, NgxMatTimepickerModule } from 'ngx-mat-datetime-picker';`

**Comment by h2qutc** [comment]
If you can provide an example [stackblitz.com](stackblitz.com), then it will be useful 😄. 
Can you try that: 
```
@ViewChild('startDate',{static: false}) public startDatePicker: any;
@ViewChild('endDate',{static: false}) public endDatePicker: any;
```

**Comment by klimtron** [comment]
This way it goes "ERROR TypeError: Cannot read property 'close' of undefine". I'll try to reproduce it on stackblitz.com. Thank you.

**Comment by klimtron** [comment]
At https://stackblitz.com/edit/demo-ngx-mat-datetime-picker demo, I've tried to add `(click)="picker.open()"` 
to the first input 
`<input matInput [ngxMatDatetimePicker]="picker" placeholder="Choose a date" [formControl]="dateControl" [min]="minDate" [max]="maxDate" [disabled]="disabled" (click)="picker.open()">`
and it does not work. Maybe somehow it's connected?

**Comment by klimtron** [comment]
`	@ViewChild('startDate') public startDatePicker: MatDatepicker<any>;
	@ViewChild('endDate') public endDatePicker: MatDatepicker<any>;

this.startDatePicker.close();`
