### ISSUE TITLE
Datetime Picker Not Showing Time Spinners

### ISSUE THREAD

**Issue by mwenechac-sys** [h2qutc/angular-material-components#58]
After implementing the date time picker. The time picker is not being rendered properly: Anything I can do to resolve this?

![image](https://user-images.githubusercontent.com/58766400/84781308-f5d5f480-afe6-11ea-80a3-03a9e033bb59.png)

**Comment by h2qutc** [comment]
Add the Material Design icon font to your index.html

<link href="https://fonts.googleapis.com/icon?family=Material+Icons&display=block" rel="stylesheet">

**Comment by mwenechac-sys** [comment]
Done thanks
