### ISSUE TITLE
Error in attempting to import _MatInputMixinBase

### ISSUE THREAD

**Issue by TusharRajGupt** [h2qutc/angular-material-components#64]
The last line of the imports:
`import { _MatInputMixinBase, MatInputModule } from '@angular/material/input';`

attempts to import _MatInputMixinBase which is never exported by the latest version of `@angular/material/input`.
This results in a build error and thus I'm unable to use the plugin.

Please look into this.

**Comment by h2qutc** [comment]
@TusharRajGupt  If you use Angular 10, can you check the version v4.0.0 out ? I think that this bug is fixed in latest version
```
npm install --save @angular-material-components/file-input@4.0.0
```

**Comment by TusharRajGupt** [comment]
Yes, upgrading to angular 10 and using the latest version fixed the issue. Thanks @h2qutc .
Another thing. I have a feature request. Can we have a [maxSize] input so that if the user uploads any file larger than the value passed, it fails validation and an error is shown? Do you think that is doable?
