### ISSUE TITLE
ERROR TypeError: c.toHexString is not a function

### ISSUE THREAD

**Issue by mohamedjarray** [h2qutc/angular-material-components#74]
I used color-picker module and I faced this error
![Untitled](https://user-images.githubusercontent.com/56433583/86645299-2ef5f900-bfd6-11ea-8e4f-1dd2b812a960.png)

**Comment by h2qutc** [comment]
@mohamedjarray Can you let me know which Angular version that you used ?

**Comment by mohamedjarray** [comment]
@h2qutc, I use angular 9

**Comment by mohamedjarray** [comment]
@h2qutc I bound my input to string, that's why this error appeared. I fixed it by passing a color object to the form.
Thanks.
