### ISSUE TITLE
@angular-material-components/datetime-picker - Angular Material Datepicker no Exported member DateRange

### ISSUE THREAD

**Issue by mwiginton** [h2qutc/angular-material-components#75]
Currently I'm on angular material 9.2.4 and am getting the error message as displayed in the screenshot. According to the docs this should be compatible with Angular Material 9.x. Any suggestions on how to resolve this urgent issue?

![Capture](https://user-images.githubusercontent.com/5847076/86833008-8f307d80-c05e-11ea-9ed7-784112ded2bf.PNG)

**Comment by talarcon** [comment]
I had the same problem today, but the following helped me
npm i @angular-material-components/datetime-picker@2.0.0 --save

**Comment by h2qutc** [comment]
@mwiginton The latest version 4.x.x supports Angular 10. For Angular 9, you should use the version 2.x by using this command:

```
npm i @angular-material-components/datetime-picker@2.0.4 --save
```

**Comment by jeremylcarter** [comment]
> @mwiginton The latest version 4.x.x supports Angular 10. For Angular 9, you should use the version 2.x by using this command:
> 
> ```
> npm i @angular-material-components/datetime-picker@2.0.4 --save
> ```

Thanks!

**Comment by mwiginton** [comment]
Thank you all so much for your advice. I was able to try this out and was able to get my project to compile with no problems. Really appreciate the quick turnaround time on my question. I'm pretty confident this tool will help us in solving our particular problem.
