### ISSUE TITLE
Datetime picker not working for Angular 10

### ISSUE THREAD

**Issue by krish016** [h2qutc/angular-material-components#76]
HI , 
we have updated our project to Angular 10 the datetime picker is not working.
Please help support the datetime picker for Angular 10

**Comment by h2qutc** [comment]
@krish016  Did you try the latest version v4.0.0 ?

**Comment by krish016** [comment]
Let me try that and will let you know. 
Thank you Hqho

**Comment by pepe19000** [comment]
Working on Angular 10. I updated to v4.0.0 and it work. Thank you your fast fix.

**Comment by krish016** [comment]
The date picker is working after updating to v4.0.0 , but the Hours and Minutes is not showing values.
Attached the screen shot for it.
<img width="320" alt="Screenshot 2020-07-09 at 2 06 59 PM" src="https://user-images.githubusercontent.com/62033555/87026212-4842a500-c190-11ea-82d5-205df1b3328f.png">

**Comment by krish016** [comment]
@h2qutc 
> The date picker is working after updating to v4.0.0 , but the Hours and Minutes is not showing values.
> Attached the screen shot for it.
> <img alt="Screenshot 2020-07-09 at 2 06 59 PM" width="320" src="https://user-images.githubusercontent.com/62033555/87026212-4842a500-c190-11ea-82d5-205df1b3328f.png">

**Comment by MDzyga** [comment]
After selecting the date with set disableMinute=true, control shows date with time

**Comment by h2qutc** [comment]
@krish016 Did you solve the problem ? 
FYI: The new version datepicker v.4.0.1 has already been released.

**Comment by krish016** [comment]
HI @h2qutc , the problem is solved.
Thank you very much.

**Comment by humblepie** [comment]
I am having the same issue with the time component not working in Angular 10 and version 4.0.2.  Time spinner controls show, but value is not bound to set Date and clicking on the spinner does nothing.  No errors show in the console either.

"@angular/common": "^10.0.11",
"@angular/material": "^10.1.3",
"@angular-material-components/datetime-picker": "^4.0.2",

![Time component not working](https://user-images.githubusercontent.com/7416135/90983710-b6bba680-e535-11ea-9ae5-b8cb995aaaac.png)
