### ISSUE TITLE
Angular 10 error

### ISSUE THREAD

**Issue by jpike88** [h2qutc/angular-material-components#84]
```ERROR TypeError: Class constructor DateAdapter cannot be invoked without 'new' at DatetimeAdapter.NgxMatDateAdapter```

**Comment by jpike88** [comment]
@h2qutc your angular dependencies might need to be updated to 10.0.5 when testing,

My versions are 

```
 "@angular-material-components/datetime-picker": "^4.0.0",
        "@angular-material-components/moment-adapter": "^4.0.0",
        "@angular/animations": "^10.0.5",
        "@angular/cdk": "^10.1.0",
        "@angular/common": "^10.0.5",
        "@angular/compiler": "^10.0.5",
        "@angular/core": "^10.0.5",
        "@angular/flex-layout": "^9.0.0-beta.29",
        "@angular/forms": "^10.0.5",
        "@angular/material": "^10.1.0",
        "@angular/material-moment-adapter": "^10.1.0",
        "@angular/platform-browser": "^10.0.5",
        "@angular/platform-browser-dynamic": "^10.0.5",
        "@angular/router": "^10.0.5",
```

**Comment by jpike88** [comment]
@h2qutc your moment adapter is not in your tests, or used in ```ng serve```!!!

I'm making a PR for you, I really hope I have your attention on this.

**Comment by h2qutc** [comment]
@jpike88  thanks a lot for your supporting ;) I will check and try to release a new version that works well with angular 10.

**Comment by jpike88** [comment]
I'm making a PR in the next few minutes, if you could accept and release asap that would be good.

**Comment by jpike88** [comment]
I'm not totally sure I actually fixed the issue, but there were a couple of build errors and I've corrected them.

If you could confirm whether you can reproduce the above error that would be good

**Comment by jpike88** [comment]
looks like it could be this.

https://github.com/angular/angular-cli/issues/18067

closing and figuring out another way
