### ISSUE TITLE
Add support for date-time range 

### ISSUE THREAD

**Issue by chezih** [h2qutc/angular-material-components#88]
Since Angular material version 10 it possible to choose date range
It will be nice if you can implement date-time range

Thanks

**Comment by h2qutc** [comment]
@chezih Yes, a datetime-range components is in progress. It will be released soon.

**Comment by jawahar95** [comment]
Hi  Am using this package in my component  am getting error while run  ng serve
![datetimepicker](https://user-images.githubusercontent.com/36267622/93431228-786d9900-f8e1-11ea-9af1-148a3ffe471b.png)

**Comment by jigneshk5** [comment]
@h2qutc any update on datetime-range component?

**Comment by TimJ0212** [comment]
@h2qutc Just asking again to make sure. Is the range component out now? I can't find it.

**Comment by EdvinM** [comment]
Why was this issue closed without any label or response? Is this range picker already available?
