### ISSUE TITLE
ERROR TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.

### ISSUE THREAD

**Issue by tenglongroy** [h2qutc/angular-material-components#89]
I tried with below code, pass compiling, but when going into the page with the date picker, it throws error like below. Also the spinner in date picker doesn't work.

```
<mat-form-field>
  <input matInput [ngxMatDatetimePicker]="picker">
  <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
  <ngx-mat-datetime-picker #picker></ngx-mat-datetime-picker>
</mat-form-field>
```

Below is the error stack.

core.js:4196 ERROR TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at subscribeTo (subscribeTo.js:27)
    at subscribeToResult (subscribeToResult.js:11)
    at MergeMapSubscriber._innerSub (mergeMap.js:59)
    at MergeMapSubscriber._tryNext (mergeMap.js:53)
    at MergeMapSubscriber._next (mergeMap.js:36)
    at MergeMapSubscriber.next (Subscriber.js:49)
    at Observable._subscribe (subscribeToArray.js:3)
    at Observable._trySubscribe (Observable.js:42)
    at Observable.subscribe (Observable.js:28)
    at MergeMapOperator.call (mergeMap.js:21)

I tried to reproduce this bug on Stackblitz (https://stackblitz.com/edit/angular-ivy-hfg2a4), but it throws error:
Error in ~/src/main.ts
ngcc failed to run on @angular-material-components/moment-adapter@4.0.1, @angular-material-components/datetime-picker@4.0.1.

version: 
Angular 10
"@angular-material-components/datetime-picker": "^4.0.1",
"@angular-material-components/moment-adapter": "^4.0.1",

**Comment by achablowski** [comment]
Hello,

Same issue here, the component seems to be working properly, but i have this exception in my console.

Angular 10, and datetimepicker 4.0.1 (Im not using moment-adapter)

**Comment by h2qutc** [comment]
@tenglongroy  @achablowski  I could reproduce this bug. I am trying to fix it soon.

**Comment by tenglongroy** [comment]
@achablowski  at first I tried without moment-adapter but also throws error

**Comment by tenglongroy** [comment]
@h2qutc thanks mate! looking forward to it.

**Comment by Wallnussfolie** [comment]
I am experiecning the same issue with version 2.0.4. Glad that I'm not the only one with this problem.

**Comment by nikolaifedorov** [comment]
Hello @h2qutc 
Maybe I can help you ;)

As I can see, error related to:
`
_watchStateChanges() {
        const datepickerStateChanged = this.datepicker ? this.datepicker._stateChanges : of();
        const inputStateChanged = this.datepicker && this.datepicker._datepickerInput ?
            this.datepicker._datepickerInput._stateChanges : of();
        const datepickerToggled = this.datepicker ?
            merge(this.datepicker.openedStream, this.datepicker.closedStream) :
            of();
        this._stateChanges.unsubscribe();
        this._stateChanges = merge(this._intl.changes, datepickerStateChanged, inputStateChanged, datepickerToggled).subscribe(() => this._changeDetectorRef.markForCheck());
    }
`
Your picker does not have `_stateChanges`.
See:
https://github.com/angular/components/blob/3828b7e2e8e4a00d33892c9f5de3f8fad55fd01b/src/material/datepicker/datepicker-base.ts#L373

Seems like you use:
`
  /** Emits new selected date when selected date changes. */
  readonly _selectedChanged = new Subject<D>();
`
but Material v.10 datepicker use:
`
  /** Emits when the datepicker's state changes. */
  readonly _stateChanges = new Subject<void>();
`

In Material v.9.2 was:
`
  /** Emits new selected date when selected date changes. */
  readonly _selectedChanged = new Subject<D>();
`
https://github.com/angular/components/blob/9.2.x/src/material/datepicker/datepicker.ts#L301

**Comment by fjc2112** [comment]
Same here, the component works fine anyway.

**Comment by h2qutc** [comment]
@nikolaifedorov  Thank you very much. The codes that you found help me a lot.
@tenglongroy  @fjc2112 @achablowski @bluee Sorry for late reply.
A new version [@angular-material-components/datetime-picker v4.0.2](https://www.npmjs.com/package/@angular-material-components/datetime-picker) has already been released to resolve this bug. 
Thanks all for your support.

**Comment by cos60** [comment]
Hello @h2qutc ,  sorry that i meet this problem at v4.0.2, i dont konw how to resolve it. this is error at my console.
`core.js:4081 ERROR TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at subscribeTo (subscribeTo.ts:27)
    at subscribeToResult (subscribeToResult.ts:36)
    at MergeMapSubscriber._innerSub (mergeMap.ts:148)
    at MergeMapSubscriber._tryNext (mergeMap.ts:141)
    at MergeMapSubscriber._next (mergeMap.ts:125)
    at MergeMapSubscriber.next (Subscriber.ts:99)
    at Observable._subscribe (subscribeToArray.ts:9)
    at Observable._trySubscribe (Observable.ts:238)
    at Observable.subscribe (Observable.ts:219)
    at MergeMapOperator.call (mergeMap.ts:100)`

i use the component by this way, it can work but stil throw the error.

`<mat-form-field>
            <mat-label > PubTime </mat-label>
            <input matInput [ngxMatDatetimePicker]="picker" required readonly>
            <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
            <ngx-mat-datetime-picker #picker></ngx-mat-datetime-picker>
</mat-form-field>`

**Comment by jayatulsiani** [comment]
is 4.0.2 compatible with angular 7?
