### ISSUE TITLE
How do change icon Tick become string Ok 

### ISSUE THREAD

**Issue by 3s-hiep** [h2qutc/angular-material-components#91]
[](url)
![image](https://user-images.githubusercontent.com/59729672/89609228-70ade400-d8a1-11ea-9a7f-bec20c3a365d.png)

**Comment by h2qutc** [comment]
@3s-hiep From the version 5.0.2, you can customize icon/text for Apply button. Feel free to check the [Documentation and Demo here](https://h2qutc.github.io/angular-material-components/).
